### ISSUE TITLE
Overflow encountered when expanding vector

### ISSUE THREAD

**Issue by dyschwartz** [Microsoft/dafny#73] opened 2017-02-08 01:46 UTC
Can someone please explain the following output. What causes such an overflow and is there a method for avoiding such issues?

Output when verifying:
DYS (testing_dafny):dafny bug.dfy 
Dafny program verifier version 1.9.8.30829, Copyright (c) 2003-2016, Microsoft.
Prover error: line 63366 column 10: Overflow encountered when expanding vector
bug.dfy(61,6): Verification inconclusive (Impl$$_module.__default.multiplication)

Dafny program verifier finished with 14 verified, 0 errors, 1 inconclusive

Note1: in original source, line 61 is `lemma multiplication(x: List<digit>, y: List<digit>, z: List<digit>)`, below.
Note2: This is with the latest Dafny release for OS X.

Source:
```newtype digit = x: int | 0 <= x < 10
datatype List<T> = Nil | Cons(head: T, tail: List<T>)

function method n2w(n: nat): digit { (n % 10) as digit }

function method w2n(d: digit): nat { d as nat }

lemma conversion_from_int(n: nat)
    ensures w2n(n2w(n)) == n % 10 {}

lemma conversion_from_digit(d: digit)
    ensures n2w(w2n(d)) == d {}

function method n2mw(n: nat): List<digit>{ if n == 0 then Nil else Cons(n2w(n % 10), n2mw(n / 10)) }

function method mw2n(l: List<digit>): nat
{
    match l
        case Nil => 0
        case Cons(d, dl) => w2n(d) + 10*mw2n(dl)
}

lemma lemma03a(n: nat)
    ensures mw2n(n2mw(n)) == n {}

function method mult(x: List<digit>, y: List<digit>): List<digit>
	ensures mw2n(mult(x,y)) == mw2n(x) * mw2n(y)
{
	var t1 := mw2n(x);
	var t2 := mw2n(y);
	
	var z := n2mw(t1 * t2);
	assert mw2n(z) == mw2n(n2mw(t1 * t2));
	lemma03a(t1 * t2);
	assert mw2n(z) == t1 * t2;
	assert mw2n(z) == mw2n(x) * mw2n(y);

	z
}

lemma multiplication(x: List<digit>, y: List<digit>, z: List<digit>)
    ensures mult(x,y) == z ==>   mw2n(x) * mw2n(y) == mw2n(z)
{}
```

**Comment by RustanLeino** [comment] 2017-02-08 23:51
Hi,

The error message you're seeing says that the underlying SMT solver ran out of memory.  (If I add `newtype digit = x | 0 <= x < 10`, I can reproduce that behavior on my machine.)  This is one way that the verifier can tell you "I don't know".

Working with non-linear arithmetic is difficult, because the support for non-linear things in the SMT solver is limited and flaky.   When you do, a good practice is to restrict what the verifier is allowed to do.  This, too, can be flaky at times, but it is usually much better.  For your example, it seems that the `multiplication` property is already proved as a postcondition of method `mult`.  Therefore, you can restrict access to the body of function `mult` by marking it as `{:opaque}` (just before the identifier `mult`).  If you do that in your example, it verifies.  (With `{:opaque}`, if you need the body of `mult`, you have to invoke the automatically generated lemma `reveal_mult()`.)

If you care to, you could file a bug report against Z3, complaining that it uses more space that you'd wish. Whether or not you do that, it will be worthwhile to get practice with `{:opaque}` if you're using non-linear multiplication.

  Rustan

**Comment by jaylorch** [comment] 2017-08-24 01:08
It seems this discussion has concluded.

**Closed by jaylorch** 2017-08-24 01:08 UTC
